# Generated by Django 3.2.9 on 2021-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('1', '디지털 드로잉'), ('2', '영상 편집'), ('3', '공예'), ('4', '요리/음료'), ('5', '베이킹/디저트'), ('6', '음악'), ('7', '댄스'), ('8', '운동'), ('9', '사진/영상'), ('10', '모션 그래픽'), ('11', '인테리어'), ('12', '제품 디자인'), ('13', 'IT'), ('14', '오피스'), ('15', '웹 디자인/웹 퍼블리셔'), ('16', '영상 편집'), ('17', '메타버스'), ('18', '영어'), ('19', '중국어'), ('20', '일본어'), ('21', '스페인어'), ('22', '불어'), ('23', '독일어')], max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
            ],
        ),
    ]
